/**
 * Environment Preparation Script (Secure)
 *
 * Reads .env file and creates a src/main/config/env-bundle.ts file
 * for production builds. This ensures environment variables
 * are bundled within the code and subjected to JavaScript obfuscation.
 */

const fs = require('fs');
const path = require('path');

function prepareEnv() {
  const rootDir = path.join(__dirname, '..');
  const envPath = path.join(rootDir, '.env');
  const outputPath = path.join(rootDir, 'src', 'main', 'config', 'env-bundle.ts');

  console.log('--- Preparing Secure Environment for Production ---');

  let envVars = {};

  if (fs.existsSync(envPath)) {
    try {
      const envContent = fs.readFileSync(envPath, 'utf8');
      envContent.split('\n').forEach((line) => {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith('#')) {
          const [key, ...valueParts] = trimmed.split('=');
          if (key && valueParts.length > 0) {
            const value = valueParts
              .join('=')
              .trim()
              .replace(/^["']|["']$/g, '');
            envVars[key.trim()] = value;
          }
        }
      });
      console.log(
        `[PREPARE_ENV] Successfully read ${Object.keys(envVars).length} env variables from .env`
      );
    } catch (error) {
      console.error('[PREPARE_ENV] Error reading .env file:', error);
      process.exit(1);
    }
  } else {
    console.warn('[PREPARE_ENV] Warning: .env file not found at', envPath);
    console.warn('[PREPARE_ENV] Production app will use default/placeholder values.');
  }

  try {
    const fileContent = `/**
 * Bundled Environment Variables (Secure)
 * 
 * This file is automatically generated by scripts/prepare-env.js during the build process.
 * Do not edit this file manually.
 */
export const bundledEnv: Record<string, string> = ${JSON.stringify(envVars, null, 2)};
`;

    // Ensure directory exists
    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, fileContent);
    console.log(
      `[PREPARE_ENV] Successfully bundled secrets to ${outputPath} (Obfuscation pending)`
    );
  } catch (error) {
    console.error('[PREPARE_ENV] Error generating env-bundle.ts:', error);
    process.exit(1);
  }
}

prepareEnv();
